"""Render a report projection to a portable Markdown document."""

from __future__ import annotations

from app.models import Report


def render_markdown(report: Report) -> str:
    doc = report.document or {}
    meta = doc.get("meta", {})
    lines: list[str] = [
        f"# {report.product_name} — Software Intelligence Report",
        "",
        f"> {report.headline}",
        "",
        f"- **Target:** {report.target_url}",
        f"- **Overall confidence:** {report.overall_confidence}% ({meta.get('confidence_band', 'n/a')})",
        f"- **Pages explored:** {report.pages_explored}",
        f"- **Evidence points:** {report.evidence_count}",
        f"- **Generated by:** {report.model_name}",
        "",
        "## Overview",
        "",
        report.summary,
        "",
    ]

    def section(title: str, key: str) -> None:
        data = doc.get(key)
        if not data:
            return
        lines.append(f"## {title}")
        if data.get("summary"):
            lines.append("")
            lines.append(f"_{data['summary']}_  (confidence {data.get('confidence', 0)}%)")
        lines.append("")

    section("Architecture", "architecture")
    for node in doc.get("architecture", {}).get("nodes", []):
        lines.append(f"- **{node['label']}** ({node['kind']}) — {node['confidence']}%")
    lines.append("")

    section("Tech stack", "tech_stack")
    for tech in doc.get("tech_stack", {}).get("items", []):
        ev = "; ".join(tech.get("evidence", [])[:2])
        lines.append(f"- **{tech['name']}** — {tech['category']} · {tech['confidence']}%" + (f" ({ev})" if ev else ""))
    lines.append("")

    section("Features", "features")
    for feat in doc.get("features", {}).get("items", []):
        lines.append(f"- **{feat['name']}** ({feat['confidence']}%) — {feat['description']}")
    lines.append("")

    section("Entities", "entities")
    for entity in doc.get("entities", {}).get("items", []):
        lines.append(f"- **{entity['name']}**: {', '.join(entity['fields'])} — {entity['confidence']}%")
    lines.append("")

    section("Engineering insights", "insights")
    for insight in doc.get("insights", {}).get("items", []):
        lines.append(f"- **{insight['title']}** ({insight['confidence']}%, {insight['classification']}) — {insight['detail']}")
    lines.append("")

    section("Security", "security")
    for item in doc.get("security", {}).get("items", []):
        lines.append(f"- **{item['title']}** ({item['confidence']}%) — {item['detail']}")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("Generated by Orbit — evidence-backed software intelligence. Inferences are labeled and carry confidence scores.")
    return "\n".join(lines)
